        // v0.33.0 — Model catalog (28 current models, +5 from v0.28.1)
        // API spec types: an = "chatComplete", ln = "responses"
        // Provider constants: Gt.ANTHROPIC, Gt.OPENAI, Kt = gateway (Vercel/Baseten/etc)
        // Free tier default: cn = "Qwen/Qwen3.7-Max-Free"
        (un = {
          SONNET_4_6: {
            id: "claude-sonnet-4-6",
            inputModalities: ["text", "image"],    // NEW in v0.33.0
            provider: Gt.ANTHROPIC,
            spec: an,  // "chatComplete"
            label: "Claude Sonnet 4.6",
            name: "Claude Sonnet 4.6",
            description: "best combo of speed & intelligence (recommended)",
            reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
            contextWindow: 1e6,
          },
          OPUS_4_8: {                              // NEW in v0.33.0
            id: "claude-opus-4-8",
            inputModalities: ["text", "image"],
            provider: Gt.ANTHROPIC,
            spec: an,
            label: "Claude Opus 4.8",
            name: "Claude Opus 4.8",
            description: "most intelligent for agents and coding",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
            contextWindow: 1e6,
          },
          OPUS_4_7: {
            id: "claude-opus-4-7",
            inputModalities: ["text", "image"],
            provider: Gt.ANTHROPIC,
            spec: an,
            label: "Claude Opus 4.7",
            name: "Claude Opus 4.7",
            description: "prev flagship, still strong for agents and coding",  // CHANGED
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high", "xhigh", "max"],
            contextWindow: 1e6,
          },
          HAIKU_4_5: {
            id: "claude-haiku-4-5-20251001",
            provider: Wt.ANTHROPIC,
            spec: on,
            label: "Claude Haiku 4.5",
            name: "Claude Haiku 4.5",
            description: "fastest & most compact, great for quick tasks",
            contextWindow: 2e5,
          },
          GPT_5_5: {
            id: "gpt-5.5",
            provider: Wt.OPENAI,
            spec: sn,
            label: "GPT-5.5",
            name: "GPT-5.5",
            description: "latest frontier model for general complex work",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high", "xhigh"],
          },
          GPT_5_4: {
            id: "gpt-5.4",
            provider: Wt.OPENAI,
            spec: sn,
            label: "GPT-5.4",
            name: "GPT-5.4",
            description: "frontier model for general complex work",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high", "xhigh"],
            contextWindow: 4e5,
          },
          GPT_5_3_CODEX: {
            id: "gpt-5.3-codex",
            provider: Wt.OPENAI,
            spec: sn,
            label: "GPT-5.3 Codex",
            name: "GPT-5.3 Codex",
            description: "frontier coding model",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high", "xhigh"],
            contextWindow: 4e5,
          },
          GPT_5_4_MINI: {
            id: "gpt-5.4-mini",
            provider: Wt.OPENAI,
            spec: sn,
            label: "GPT-5.4 Mini",
            name: "GPT-5.4 Mini",
            description: "fast, cost-effective model for everyday tasks",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high"],
            contextWindow: 4e5,
          },
          KIMI_K2_6: {
            id: "moonshotai/Kimi-K2.6",
            provider: Qt,
            spec: on,
            label: "Kimi K2.6",
            name: "Kimi K2.6",
            description: "long-horizon coding with vision",
            contextWindow: 256e3,
          },
          KIMI_K2_5: {
            id: "moonshotai/Kimi-K2.5",
            provider: Qt,
            spec: on,
            label: "Kimi K2.5",
            name: "Kimi K2.5",
            description: "multimodal frontend coding",
            contextWindow: 256e3,
          },
          GLM_5_1: {
            id: "zai-org/GLM-5.1",
            provider: Qt,
            spec: on,
            label: "GLM-5.1",
            name: "GLM-5.1",
            description: "long-horizon autonomous coding agent",
          },
          GLM_5: {
            id: "zai-org/GLM-5",
            provider: Qt,
            spec: on,
            label: "GLM-5",
            name: "GLM-5",
            description: "multi-mode thinking & long-range planning",
            contextWindow: 2e5,
          },
          MINIMAX_M3: {                              // NEW in v0.33.0
            id: "MiniMaxAI/MiniMax-M3",
            inputModalities: ["text", "image"],
            provider: Kt,
            spec: an,
            label: "MiniMax M3",
            name: "MiniMax M3",
            description: "frontier coding, agents & native multimodality",
            reasoning: !0,
            contextWindow: 1e6,
          },
          MINIMAX_M2_7: {
            id: "MiniMaxAI/MiniMax-M2.7",
            inputModalities: ["text"],
            provider: Kt,
            spec: an,
            label: "MiniMax M2.7",
            name: "MiniMax M2.7",
            description: "end-to-end software engineering agent",
          },
          MINIMAX_M2_5: {
            id: "MiniMaxAI/MiniMax-M2.5",
            inputModalities: ["text"],
            provider: Kt,
            spec: an,
            label: "MiniMax M2.5",
            name: "MiniMax M2.5",
            description: "cross-platform full-stack agentic dev",
            contextWindow: 2e5,
          },
          DEEPSEEK_V4_PRO: {
            id: "deepseek/deepseek-v4-pro",
            provider: Qt,
            spec: on,
            label: "DeepSeek V4 Pro",
            name: "DeepSeek V4 Pro",
            description: "hybrid-attention long-context reasoning",
            reasoning: !0,
            reasoningEfforts: ["high", "max"],
            contextWindow: 1e6,
          },
          DEEPSEEK_V4_FLASH: {
            id: "deepseek/deepseek-v4-flash",
            provider: Qt,
            spec: on,
            label: "DeepSeek V4 Flash",
            name: "DeepSeek V4 Flash",
            description: "fast hybrid-attention reasoning",
            reasoning: !0,
            reasoningEfforts: ["high", "max"],
            contextWindow: 1e6,
          },
          QWEN_3_6_MAX_PREVIEW: {
            id: "Qwen/Qwen3.6-Max-Preview",
            provider: Qt,
            spec: on,
            label: "Qwen 3.6 Max Preview",
            name: "Qwen 3.6 Max Preview",
            description: "vibe coding & efficient agent execution",
            reasoning: !0,
          },
          QWEN_3_6_PLUS: {
            id: "Qwen/Qwen3.6-Plus",
            provider: Qt,
            spec: on,
            label: "Qwen 3.6 Plus",
            name: "Qwen 3.6 Plus",
            description: "agentic coding & reasoning",
            reasoning: !0,
          },
          QWEN_3_7_MAX: {
            id: "Qwen/Qwen3.7-Max",
            inputModalities: ["text"],
            provider: Kt,
            spec: an,
            label: "Qwen 3.7 Max",
            name: "Qwen 3.7 Max",
            description: "frontier coding & long-horizon agent execution",
            reasoning: !0,
            contextWindow: 1e6,
          },
          QWEN_3_7_PLUS: {                            // NEW in v0.33.0
            id: "Qwen/Qwen3.7-Plus",
            inputModalities: ["text", "image"],
            provider: Kt,
            spec: an,
            label: "Qwen 3.7 Plus",
            name: "Qwen 3.7 Plus",
            description: "agentic coding & reasoning at lower cost",
            reasoning: !0,
            contextWindow: 1e6,
          },
          STEP_3_7_FLASH: {                            // NEW in v0.33.0
            id: "stepfun/Step-3.7-Flash",
            inputModalities: ["text", "image"],
            provider: Kt,
            spec: an,
            label: "Step 3.7 Flash",
            name: "Step 3.7 Flash",
            description: "multimodal sparse-MoE reasoning",
            reasoning: !0,
            contextWindow: 256e3,
          },
          STEP_3_5_FLASH: {
            id: "stepfun/Step-3.5-Flash",
            inputModalities: ["text"],
            provider: Kt,
            spec: an,
            label: "Step 3.5 Flash",
            name: "Step 3.5 Flash",
            description: "fast sparse-MoE agentic reasoning",
            reasoning: !0,
            contextWindow: 1e6,
          },
          XIAOMI_MIMO_V2_5_PRO: {
            id: "xiaomi/mimo-v2.5-pro",
            provider: Qt,
            spec: on,
            label: "MiMo V2.5 Pro",
            name: "MiMo V2.5 Pro",
            description: "high-capability long-context agentic coding",
            contextWindow: 1e6,
          },
          XIAOMI_MIMO_V2_5: {
            id: "xiaomi/mimo-v2.5",
            provider: Qt,
            spec: on,
            label: "MiMo V2.5",
            name: "MiMo V2.5",
            description: "efficient long-context agentic coding",
            contextWindow: 1e6,
          },
          GEMINI_3_5_FLASH: {
            id: "google/gemini-3.5-flash",
            provider: Qt,
            spec: on,
            label: "Gemini 3.5 Flash",
            name: "Gemini 3.5 Flash",
            description:
              "Pro-level coding proficiency, parallel agentic execution",
            vendorLabel: "Google",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high"],
            contextWindow: 1e6,
          },
          GEMINI_3_1_FLASH_LITE: {
            id: "google/gemini-3.1-flash-lite",
            inputModalities: ["text", "image"],
            provider: Kt,
            spec: an,
            label: "Gemini 3.1 Flash Lite",
            name: "Gemini 3.1 Flash Lite",
            description: "high-volume workhorse model with implicit caching",
            vendorLabel: "Google",
            reasoning: !0,
            reasoningEfforts: ["low", "medium", "high"],
            contextWindow: 1e6,
          },
          NEMOTRON_3_ULTRA: {                          // NEW in v0.33.0
            id: "nvidia/nemotron-3-ultra-550b-a55b",
            inputModalities: ["text"],
            provider: Kt,
            spec: an,
            label: "Nemotron 3 Ultra",
            name: "Nemotron 3 Ultra",
            description: "open reasoning model for long-horizon autonomous agents",
            reasoning: !0,
            contextWindow: 1e6,
          },
        }).SONNET_4_6.id,
        un.OPUS_4_8.id,
        un.OPUS_4_7.id,
        un.HAIKU_4_5.id,
        (ln = [
          {
            canonicalId: "zai-org/GLM-5",
            providers: {
              [Wt.VERCEL_AI_GATEWAY]: "zai/glm-5",
              [Wt.BASETEN]: "zai-org/GLM-5",
            },
          },
          {
            canonicalId: "zai-org/GLM-5.1",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "zai/glm-5.1" },
          },
          {
            canonicalId: "moonshotai/Kimi-K2.5",
            providers: {
              [Wt.VERCEL_AI_GATEWAY]: "moonshotai/kimi-k2.5",
              [Wt.BASETEN]: "moonshotai/Kimi-K2.5",
              [Wt.CLOUDFLARE_AI_GATEWAY]: "workers-ai/@cf/moonshotai/kimi-k2.5",
            },
          },
          {
            canonicalId: "moonshotai/Kimi-K2.6",
            providers: {
              [Wt.VERCEL_AI_GATEWAY]: "moonshotai/kimi-k2.6",
              [Wt.BASETEN]: "moonshotai/Kimi-K2.6",
              [Wt.CLOUDFLARE_AI_GATEWAY]: "workers-ai/@cf/moonshotai/kimi-k2.6",
            },
          },
          {
            canonicalId: "MiniMaxAI/MiniMax-M2.5",
            providers: {
              [Wt.VERCEL_AI_GATEWAY]: "minimax/minimax-m2.5",
              [Wt.BASETEN]: "MiniMaxAI/MiniMax-M2.5",
            },
          },
          {
            canonicalId: "deepseek/deepseek-v4-pro",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "deepseek/deepseek-v4-pro" },
          },
          {
            canonicalId: "deepseek/deepseek-v4-flash",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "deepseek/deepseek-v4-flash" },
          },
          {
            canonicalId: "Qwen/Qwen3.6-Max-Preview",
            providers: {
              [Wt.VERCEL_AI_GATEWAY]: "alibaba/qwen-3.6-max-preview",
            },
          },
          {
            canonicalId: "Qwen/Qwen3.6-Plus",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "alibaba/qwen3.6-plus" },
          },
          {
            canonicalId: "Qwen/Qwen3.7-Max",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "alibaba/qwen3.7-max" },
          },
          {
            canonicalId: "Qwen/Qwen3.7-Plus",                                   // NEW
            providers: { [Gt.VERCEL_AI_GATEWAY]: "alibaba/qwen3.7-plus" },
          },
          {
            canonicalId: "MiniMaxAI/MiniMax-M3",                                 // NEW
            providers: { [Gt.VERCEL_AI_GATEWAY]: "minimax/minimax-m3" },
          },
          {
            canonicalId: "MiniMaxAI/MiniMax-M2.7",
            providers: { [Gt.VERCEL_AI_GATEWAY]: "minimax/minimax-m2.7" },
          },
          {
            canonicalId: "stepfun/Step-3.7-Flash",                               // NEW
            providers: { [Gt.VERCEL_AI_GATEWAY]: "stepfun/step-3.7-flash" },
          },
          {
            canonicalId: "stepfun/Step-3.5-Flash",
            providers: { [Gt.OPENROUTER]: "stepfun/step-3.5-flash" },
          },
          {
            canonicalId: "xiaomi/mimo-v2.5-pro",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "xiaomi/mimo-v2.5-pro" },
          },
          {
            canonicalId: "xiaomi/mimo-v2.5",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "xiaomi/mimo-v2.5" },
          },
          {
            canonicalId: "google/gemini-3.5-flash",
            providers: { [Wt.VERCEL_AI_GATEWAY]: "google/gemini-3.5-flash" },
          },
          {
            canonicalId: "google/gemini-3.1-flash-lite",
            providers: {
              [Gt.VERCEL_AI_GATEWAY]: "google/gemini-3.1-flash-lite",
            },
          },
          {
            canonicalId: "nvidia/nemotron-3-ultra-550b-a55b",                    // NEW
            providers: { [Gt.VERCEL_AI_GATEWAY]: "nvidia/nemotron-3-ultra-550b-a55b" },
          },
        ]),
        // Legacy aliases — unchanged from v0.28.1
        (mn = {
          "claude-sonnet-4-20250514": un.SONNET_4_6.id,
          "claude-sonnet-4-5-20250929": un.SONNET_4_6.id,
          "claude-opus-4-5-20251101": un.OPUS_4_7.id,
          "claude-opus-4-6": un.OPUS_4_7.id,
          "claude-haiku-4-5": un.HAIKU_4_5.id,
        }),
        (pn = un.KIMI_K2_5.id),
        (dn = {
          [Gt.ANTHROPIC]: "Anthropic",
          [Gt.OPENAI]: "OpenAI",
          [Gt.BASETEN]: "Open Source",
          [Gt.VERCEL_AI_GATEWAY]: "Open Source",
