        // ══════════════════════════════════════════════════════════
        // v0.33.0 — Pricing & Subscription Plans
        //
        // Variable mapping:
        //   Yt  = PRICING_TABLE (per-provider pricing arrays)
        //   Wt  = PROVIDER (enum)
        //   Jt  = PLAN_BUDGETS (per-plan budget limits)
        //   Xt  = PLAN_DISPLAY_NAMES
        //   Zt  = PLAN_RESTRICTIONS (allowed categories + blocked models)
        //   en  = PLAN_ORDER (plan ID array)
        //
        // Pricing is per 1M tokens. Categories: "premium" | "opensource"
        // ══════════════════════════════════════════════════════════
        (Yt /* PRICING_TABLE */ = {
          [Wt.ANTHROPIC]: [
            {
              id: "anthropic:claude-sonnet-4-20250514",
              provider: "Anthropic",
              category: "premium",
              promptCost: 3,
              completionCost: 15,
              cacheWrite5mCost: 3.75,
              cacheWrite1hCost: 6,
              cacheHitCost: 0.3,
            },
            {
              id: "anthropic:claude-sonnet-4-5-20250929",
              provider: "Anthropic",
              category: "premium",
              promptCost: 3,
              completionCost: 15,
              cacheWrite5mCost: 3.75,
              cacheWrite1hCost: 6,
              cacheHitCost: 0.3,
            },
            {
              id: "anthropic:claude-opus-4-5-20251101",
              provider: "Anthropic",
              category: "premium",
              promptCost: 5,
              completionCost: 25,
              cacheWrite5mCost: 6.25,
              cacheWrite1hCost: 10,
              cacheHitCost: 0.5,
            },
            {
              id: "anthropic:claude-sonnet-4-6",
              provider: "Anthropic",
              category: "premium",
              promptCost: 3,
              completionCost: 15,
              cacheWrite5mCost: 3.75,
              cacheWrite1hCost: 6,
              cacheHitCost: 0.3,
            },
            {
              id: "anthropic:claude-opus-4-8",        // NEW in v0.33.0
              provider: "Anthropic",
              category: "premium",
              promptCost: 5,
              completionCost: 25,
              cacheWrite5mCost: 6.25,
              cacheWrite1hCost: 10,
              cacheHitCost: 0.5,
            },
            {
              id: "anthropic:claude-opus-4-7",
              provider: "Anthropic",
              category: "premium",
              promptCost: 5,
              completionCost: 25,
              cacheWrite5mCost: 6.25,
              cacheWrite1hCost: 10,
              cacheHitCost: 0.5,
            },
            {
              id: "anthropic:claude-opus-4-6",
              provider: "Anthropic",
              category: "premium",
              promptCost: 5,
              completionCost: 25,
              cacheWrite5mCost: 6.25,
              cacheWrite1hCost: 10,
              cacheHitCost: 0.5,
            },
            {
              id: "anthropic:claude-haiku-4-5-20251001",
              provider: "Anthropic",
              category: "premium",
              promptCost: 1,
              completionCost: 5,
              cacheWrite5mCost: 1.25,
              cacheWrite1hCost: 2,
              cacheHitCost: 0.1,
            },
          ],
          [Wt.OPENAI]: [
            {
              id: "openai:gpt-5.5",
              provider: "OpenAI",
              category: "premium",
              promptCost: 5,
              completionCost: 30,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0.5,
            },
            {
              id: "openai:gpt-5.4",
              provider: "OpenAI",
              category: "premium",
              promptCost: 2.5,
              completionCost: 15,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0.25,
            },
            {
              id: "openai:gpt-5.3-codex",
              provider: "OpenAI",
              category: "premium",
              promptCost: 2,
              completionCost: 8,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0.5,
            },
            {
              id: "openai:gpt-5.4-mini",
              provider: "OpenAI",
              category: "premium",
              promptCost: 0.75,
              completionCost: 4.5,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0.075,
            },
          ],
          [Wt.BASETEN]: [
            {
              id: "baseten:zai-org/GLM-5",
              provider: "Baseten",
              category: "opensource",
              promptCost: 0.95,
              completionCost: 3.15,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0,
            },
            {
              id: "baseten:moonshotai/Kimi-K2.5",
              provider: "Baseten",
              category: "opensource",
              promptCost: 0.6,
              completionCost: 3,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0,
            },
            {
              id: "baseten:moonshotai/Kimi-K2.6",
              provider: "Baseten",
              category: "opensource",
              promptCost: 0.95,
              completionCost: 4,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0.16,
            },
            {
              id: "baseten:MiniMaxAI/MiniMax-M2.5",
              provider: "Baseten",
              category: "opensource",
              promptCost: 0.5,
              completionCost: 2,
              cacheWrite5mCost: 0,
              cacheWrite1hCost: 0,
              cacheHitCost: 0,
            },
          ],
          [Wt.VERCEL_AI_GATEWAY]: [],
          [Wt.OPENROUTER]: [],
        }),
        __name(getModelCategory, "getModelCategory"),
        (Jt /* PLAN_BUDGETS */ = {
          "individual-go": { premium: 0, opensource: 10, total: 10 },
          "individual-pro": { premium: 15, opensource: 15, total: 30 },
          "individual-max": { premium: 100, opensource: 50, total: 150 },
          "individual-ultra": { premium: 200, opensource: 100, total: 300 },
          "teams-pro": { premium: 40, opensource: 0, total: 40 },
        }),
        (Xt /* PLAN_DISPLAY_NAMES */ = {
          "individual-go": "Go",
          "individual-pro": "Pro",
          "individual-max": "Max",
          "individual-ultra": "Ultra",
          "teams-pro": "Teams Pro",
        }),
        (Zt /* PLAN_RESTRICTIONS */ = {
          "individual-go": { allowedCategories: ["opensource"] },
          "individual-pro": {
            allowedCategories: ["premium", "opensource"],
            blockedModels: [
              "anthropic:claude-opus-4-8",             // NEW in v0.33.0
              "anthropic:claude-opus-4-7",
              "anthropic:claude-opus-4-6",
              "anthropic:claude-opus-4-5-20251101",
            ],
          },
          "individual-max": { allowedCategories: ["premium", "opensource"] },
          "individual-ultra": { allowedCategories: ["premium", "opensource"] },
          "teams-pro": { allowedCategories: ["premium", "opensource"] },
        }),
        (en /* PLAN_ORDER */ = [
          "individual-go",
          "individual-pro",
          "individual-max",
          "individual-ultra",
          "teams-pro",
        ]),
